version: '3.8'

services:
  app:
    image: saroopa/pythonwebbase
    restart: on-failure
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=<provide-password-here>
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 8000:8000
    labels:
      - kompose.service.type=loadbalancer
  mysqldb:
    image: mysql/mysql-server:latest
    restart: on-failure
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=<provide-root-password-here>
      - MYSQL_PASSWORD=<provide-password-here>
    ports:
      - 3306:3306
    healthcheck:
      test: "mysqladmin -u root -p$$MYSQL_ROOT_PASSWORD ping --protocol=tcp"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

networks:
  app-network:
    driver: bridge
